spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.example.springbootdemo.entity
  configuration:
    map-underscore-to-camel-case: true
